Fix multiple issues that kills the agent
faust-streaming/faust pull request #506
Opened 2023-05-24 19:52 UTC by owen-zora

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://faust-streaming.github.io/faust/contributing.html).

## Description
see details in https://fauststreaming.slack.com/archives/C04QJNEA6S3/p1684943262108859

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

2023-05-25 15:59 UTC, wbarnha requested changes
Needs linting before further review. I don't have permission to write to your fork, so you'll need to run `./scripts/lint`.

2023-05-25 22:46 UTC, wbarnha reviewed
Neat! Thanks for the changes! I'll need a bit to read over them more to make sure it all makes sense.

2023-05-26 13:18 UTC, patkivikram commented on faust/transport/consumer.py
> +                        self.log.exception(
same as above, this will cause all messages to be acknowledge and commit their offset even when the application fails to process it

2023-05-26 17:58 UTC, owen-zora commented on faust/transport/conductor.py
> +                    return await get_callback_for_tp(tp)(message)
I know it's probably not the best solution. However, this exception kills not only the agent, but the entire faust application, which then trigger the rebalancing of the cluster. It happens pretty frequently if we have a large number of workers, then the cluster just keeps rebalancing forever.

2023-05-26 19:32 UTC, wbarnha commented on faust/transport/conductor.py
> +                    return await get_callback_for_tp(tp)(message)
What exception gets raised specifically when the cluster is undergoing re-balancing?

2023-05-26 20:46 UTC, owen-zora commented on faust/transport/conductor.py
> +                    return await get_callback_for_tp(tp)(message)
I'm getting a lot of `KeyError` in the production. Not necessarily during rebalancing, but this exception kills the faust app, then trigger rebalancing pretty frequently

2023-05-26 20:48 UTC, wbarnha commented on faust/transport/conductor.py
> +                    return await get_callback_for_tp(tp)(message)
If you could provide a traceback, I'd be grateful so it could expedite my troubleshooting.

2023-05-26 20:58 UTC, owen-zora commented on faust/transport/conductor.py
> +                    return await get_callback_for_tp(tp)(message)
basically `get_callback_for_tp` is a getter function on a map. The `tp` doesn't exist on the map. However, I'm not sure why that happens. It's throwing pretty frequently in our app.

![Screenshot 2023-05-26 at 1 56 45 PM](https://github.com/faust-streaming/faust/assets/122320573/ea714c70-97dd-4e92-9ef7-3d7d9f7f3e1d)

2023-05-28 01:16 UTC, wbarnha commented
Closing this PR for similar reasons, unfortunately. We shouldn't catch all Exceptions. I'll still try to look into what's causing your `No callback` errors.

2023-05-28 01:16 UTC, closed without merging